### ISSUE TITLE
.create method problem

### ISSUE THREAD

**Issue by GeorgeIvlev** [startupthekid/feathers-ios#15]
Hi guys!
I have a problem, can you help me please?

I have created a basic app on iOS with feathers swift library, but I have some troubles with sending requests.
When I use `feathersRestApp.authenticate` everything is fine, in my data on server I have this:
`{"email": "....", "password": ".....", "strategy": "local"}`, but, when I use `.request` method from service to create a user my server getting this data:  ` {'{"strategy":"local","email":"toto@gmail.com","password":"123123"}': '' }` all object is formed like a key, and this is on all services where I call `.. .request(.create ...` method, can you help please? Thanks.

**Comment by thebarndog** [comment]
I'm not sure exactly what would be going on here, can you post a more full code sample?

**Comment by mikegazzaruso** [comment]
Please post full/mocked code

**Comment by thebarndog** [comment]
Closing to do inactivity, feel free to open up another issue if it persists.
