### ISSUE TITLE
SocketProvider's Realtime Events not working and doubts about authentication token

### ISSUE THREAD

**Issue by mikegazzaruso** [startupthekid/feathers-ios#16]
override func viewDidLoad() {
        super.viewDidLoad()
        let feathersApp = Feathers(provider: SocketProvider(baseURL: URL(string: "https://my.backend.address")!, configuration: [], timeout: 5))
        
        feathersApp.authenticate([
            "strategy": "local",
            "email": "bla@blabla",
            "password": "password"
            ])
            .on(failed: {
                failure in
                print("Failed: \(failure.error)")
            }, value: {
                response in
                    print("Token: \(response)")
                
                let userService = feathersApp.service(path: "users")
                userService.on(event: .created)
                    .on(value: { entity in
                        print(entity) // Prints the object that was just created
                    })
            })
        .start()
    }

I launch on my terminal/real device, then I create a new user using postman, new user creates succesfully but my RealTime event trigger on .created for "users" service never get called.

Furthermore, I would ask: what is best practice to check if user did already logged in after I reopen the app on the device? I would avoid to generate a new token every time. The problem is that after authentication, If I properly understood, the JWT access token is backed up *by the application* for the further sdk methods. So, must I authenticate every time I reopen the app?

**Comment by thebarndog** [comment]
@mikegazzaruso I just tested this and I was able to receive real-time events in a sample app I have. Are you sure that your event filters are set to emit events on the server? To emit events to call clients, in your server code your filter should look like:

```js
module.exports = function (data, connection, hook) {
  return data;
};
```

re: Your question about authentication.

Right now there's no mechanism for verifying that a token is still valid. Those are coming in the not-so-far future. The JS client currently has three methods for doing so: `getJWT`, `verifyJWT`, and `payloadIsValid`. I'll be adding those along with a refresh mechanism so if any request gets a 401 it'll automatically attempt to refresh the token then replay the original request but that part is a bit farther off. It'll probably take the form of an internal hook.

**Comment by mikegazzaruso** [comment]
Hi, yes... and thus when I create a user, it enters into the function and return data, if I put a console.log(data); the server outputs new created user. But no way for me to get the data back on my iOS client. 

Furthermore, if I write down code from Basic Guides on FeathersJS site, it works when using Javascript client. (https://docs.feathersjs.com/guides/step-by-step/basic-feathers/real-time.html)

Could you provide your working code (or an excerpt) please? 

Thank you

P.S.: If I query the property supportsRealtimeEvents on my Provider it returns true

**Comment by thebarndog** [comment]
It could be a number of things, like not retaining a reference to a service/provider/feathers client or some server side configuration. Based on the code you provided, it's likely that `userService` is going out of scope because you're not retaining it anywhere.

**Comment by thebarndog** [comment]
Here's some example code of how services should be used @mikegazzaruso:

```swift

struct Providers {
    static let feathersApp = Feathers(provider: SocketProvider(baseURL: URL(string: "https://my.backend.address")!, configuration: [], timeout: 5))
}

public final class ExampleViewController: UIViewController {
    
    let userService = Providers.feathersApp.service('users')

    public override func viewDidLoad() {
        super.viewDidLoad()
        Providers.feathersApp.authenticate([
        "strategy": "local",
        "email": "bla@blabla",
        "password": "password"
        ])
        .on(failed: {
            failure in
            print("Failed: \(failure.error)")
        }, value: {
            response in
                print("Token: \(response)")
        })
    .start()
    
    userService.on(event: .created)
        .observeValues(value: { entity in
             print(entity) // Prints the object that was just created
         })
    }
}
```

**Comment by mikegazzaruso** [comment]
Hi, your code and mine are pretty the same (I don't create a struct for my Providers, but simply let feathersApp = = Feathers(provider: SocketProvider(baseURL: URL(string: "https://my.backend.address")!, configuration: [], timeout: 5))
}, no need to make it static due it's simply a test where all happens on a single ViewController, for now, next I'd like to use a Singleton class).

It's weird, how I was telling you, server-side all system go: if I follow examples I get back a feedback on creating new users, using example's listeners

**Comment by mikegazzaruso** [comment]
<img width="1165" alt="schermata 2017-07-09 alle 11 51 25" src="https://user-images.githubusercontent.com/9842486/27992817-16691d3c-649d-11e7-96d4-e2f3dee9ea51.png">

Is it normal this warning? Maybe this directive should be triggered "start()"? 
However I understand, it generates a Signal<T> and not a SignalProducer, so I cannot have a start() command on it. Maybe it is advisable to do a 

let _ = userService.on.etc.etc. (but the question is: could this have something to do with the issue)

Thanks again

**Comment by mikegazzaruso** [comment]
@startupthekid could you please give me assistance on this, ? I'm trying to get out from this but no way... which are features server-side that could cause this? I could paste here my server-side code (also if, as I wrote above, I have no problems with normal JavaScript websocket client)

**Comment by mikegazzaruso** [comment]
@startupthekid I made a short video to show you that server-side code should be ok: I created a listener on the server in javascript from another location, and all is ok. But on iOS event never get fired. Maybe being on an iOS emulator is the problem? 

Video is here:
http://www.videosprout.com/video?id=f6dc4c57-d44d-4472-a465-e4ad72457ca2

**Comment by thebarndog** [comment]
You're not observing any value from the returned `Signal`.

```swift
userService.on(event: .created)
        .observeValues(value: { entity in
             print(entity) // Prints the object that was just created
         })
    }
```

**Comment by mikegazzaruso** [comment]
this is assumed to be an error? Don t understand.. This is just from your example code.. How should I observe? 

Thanks

**Comment by mikegazzaruso** [comment]
Oh ok I just read.... Sorry I have not read the previous comment... Ok.. But so I think you should update docs with exact syntax.. Right? 

Thanks, in the next hours I will try this way

**Comment by mikegazzaruso** [comment]
@startupthekid Ok, now it works. But only a little correction: 

`userService.on(event: .created).observeValues({ entity in print(entity) })`

(without parameter name "value", only the closure that capture [String:Any] and returns Void)

Now it works like a charm. 

Thank you for the support, though I think it would be nice to update your docs... cheers!

**Comment by thebarndog** [comment]
Glad I could help! I updated the docs to reflect the correct usage.
