### ISSUE TITLE
Create method combines JSON key and value pair into a single string

### ISSUE THREAD

**Issue by AaronKovacs** [startupthekid/feathers-ios#17]
Messing around with feathers.js I stumbled across a problem with the following request on my local feathers Rest server (Database is NeDB):

`myService.request(.create(data:  ["key" : false], query: nil)).start()`

turns into this on the server:

`{"total":1,"limit":10,"skip":0,"data":[{"{\"key\":false}":"","_id":"LIjBTcAaW2U5MBid"}]}`

the problem child being:

`"{\"key\":false}":""`

Any help getting the key pairs to display properly would be appreciated.

**Comment by AaronKovacs** [comment]
Figured out a solution. In [RestProvider](https://github.com/feathersjs/feathers-swift-rest) I specified the content type in `func buildRequest`.

`urlRequest.addValue("application/json", forHTTPHeaderField: "Content-Type")`

**Comment by objectthink** [comment]
cool, worked for me, is there plans to add this to the trunk?
