### ISSUE TITLE
Get Total, Limit and Skip values

### ISSUE THREAD

**Issue by aabanaag** [startupthekid/feathers-ios#22]
How can we get the Total, limit and skip values from the response? from what've read it is being passed within the Pagination class. But `response.pagination.total` is returning an error `Value of type 'Pagination?' has no member 'total'`

**Comment by joshuacleetus** [comment]
@aabanaag I am using the below code to find it,

<img width="966" alt="screen shot 2017-11-10 at 6 21 53 pm" src="https://user-images.githubusercontent.com/2602822/32682701-66b2f0fc-c644-11e7-8658-0c9d4c7067f2.png">


See the full sample code below to make it more clear,

<img width="1073" alt="screen shot 2017-11-10 at 6 23 06 pm" src="https://user-images.githubusercontent.com/2602822/32682672-3a6ff576-c644-11e7-8608-6d6a70dd46a3.png">
