### ISSUE TITLE
service.create && service.update return FeatherError.unknow

### ISSUE THREAD

**Issue by DimitriSoucanye** [startupthekid/feathers-ios#39]

**Comment by Natelegreat1** [comment]
@DimitriSoucanye I keep getting **Feathers.FeathersNetworkError error 5.**
How do you know which error that maps to considering the FeathersNetworkError documentation is all undocumented? :( 
http://cocoadocs.org/docsets/Feathers/5.2.0/Enums/FeathersNetworkError.html
