### ISSUE TITLE
It would be really nice if this were maintained again

### ISSUE THREAD

**Issue by mroushdy** [startupthekid/feathers-ios#45]
Library needs to be updated to work with Alamofire 5.0

**Comment by daffl** [comment]
Pull requests are always welcome. I will happily give anybody who is contributing access for future maintenance.

**Comment by ericuldall** [comment]
@mroushdy if you're still in need of feathers support in swift I just started a new client for my own needs. Will be actively developing this and looking for feedback: https://github.com/ericuldall/swift-feathersjs
